---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 18 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: ["8", "11"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    if: github.repository_owner == 'openrewrite'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{secrets.WORKFLOWS_ACCESS_TOKEN}}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: build
        if: github.event_name != 'workflow_dispatch'
        run: ./mvnw --no-transfer-progress -B clean verify -DskipITs --file pom.xml
      - name: verify
        if: github.event_name != 'push'
        run: ./mvnw --no-transfer-progress -B clean verify --file pom.xml
