---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: build
        if: github.event_name != 'workflow_dispatch'
        run: ./mvnw --no-transfer-progress -B clean verify -DskipITs --file pom.xml
      - name: verify
        if: github.event_name != 'push'
        run: ./mvnw --no-transfer-progress -B clean verify --file pom.xml
